# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "maquina1" do |m1|
    m1.vm.box = "StefanScherer/windows_2019"
    m1.vm.hostname = "Win2019"
  end
  config.vm.provider "virtualbox" do |va|
    va.name = "Maquina 1 Win2019"
    va.memory = 4096
    va.cpus = 4
  end
end
Vagrant.configure("2") do |config|
  config.vm.define "maquina2" do |m2|
    m2.vm.box = "gusztavvargadr/windows-10"
    m2.vm.hostname = "Win10"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Maquina 2 Win10"
    vb.memory = 2048
    vb.cpus = 2
  end
end
