# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "web-aya"
  config.vm.synced_folder "./sync_folder","/data"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Web server"
    vb.memory = 3072 
    vb.cpus = 2
  end
  config.vm.network "private_network", ip: "172.16.0.5"
  config.vm.network "public_network", ip: "10.99.0.5"
end